name: CI & CD
on:
    push:
        branches:
            - main
        paths:
            - package.json
jobs:
    Build-and-Publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
              env:
                  HOME_PAGE: ${{github.repositoryUrl}}
                  TOPICS: idea2app,github
                  DESCRIPTION: idea2app

            - name: get content
              run: |
                  DESCRIPTION=$(node -p "JSON.parse(require('fs').readFileSync('package.json')).description || ''")
                  HOME_PAGE=$(node -p "JSON.parse(require('fs').readFileSync('package.json')).homepage || ''")
                  TOPICS=$(node -p "JSON.parse(require('fs').readFileSync('package.json')).keywords?.join(',').toLowerCase() || ''")
                  echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
                  echo "HOME_PAGE=$HOME_PAGE" >> $GITHUB_ENV
                  echo "TOPICS=$TOPICS" >> $GITHUB_ENV

            - name: edit repo info
              run: |
                  [[ "$DESCRIPTION" ]] && gh repo edit "$REPOSITORY" --description "$DESCRIPTION"
                  [[ "$HOME_PAGE" ]] && gh repo edit "$REPOSITORY" --homepage "$HOME_PAGE"
                  [[ "$TOPICS" ]] && {
                    gh api --method PUT "repos/$REPOSITORY/topics" -f "names[]"
                    gh repo edit "$REPOSITORY" --add-topic "$TOPICS"
                  }
              env:
                  # "Administration" repository permissions (write), https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#replace-all-repository-topics
                  GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
                  REPOSITORY: ${{ github.repository }}
